### ISSUE TITLE
missing class methods in v2.x

### ISSUE THREAD

**Issue by casperdcl** [NiklasRosenstein/pydoc-markdown#103]
In `pydoc-mardown>=2.1.0,<3` is seems that `@calssmethod`s have the function signature code block removed (`__doc__` still is printed correctly):

https://github.com/tqdm/tqdm.github.io/commit/47e0790821a1a254a9911772fedf60adda76d46f#diff-7b5787b899289fbc60c0aea9bda6dfc5R760-R778

**Comment by NiklasRosenstein** [comment]
Hey @casperdcl can you try v2.1.2? It should fix this issue

**Comment by casperdcl** [comment]
Yes fixed; thanks.
