### ISSUE TITLE
cannot import name 'ISO_8601' from 'nr.parsing.date'

### ISSUE THREAD

**Issue by rLoka** [NiklasRosenstein/pydoc-markdown#105]
Hi,

I installed pydoc-markdown via pip (development version on github) and when I try to run it over the command line, I get:

```
ImportError: cannot import name 'ISO_8601' from 'nr.parsing.date' (/usr/local/lib/python3.8/site-packages/nr/parsing/date.py)
```

Do you know where could be the problem?

**Comment by NiklasRosenstein** [comment]
Hey @rLoka , sorry about that, I did a mistake in publishing a new version of `nr.parsing.date` and (not adhering to semantic versioning). I removed the faulty version of that library, could you please try again?

**Comment by NiklasRosenstein** [comment]
Can confirm it's working on my side (tested in an empty environment). Let me know if you still have issues.
