### ISSUE TITLE
Hugo flavored markdown

### ISSUE THREAD

**Issue by xoxys** [NiklasRosenstein/pydoc-markdown#106]
It would be cool to have the ability to generate hugo flavored markdown, in the first step generate the front matter should be a good starter.

**Comment by genebean** [comment]
I’m particularly interested in this one as the entire reason I’m looking at this project is to create docs from multiple repositories to then publish as part of a Hugo site built with the [Docsy](https://www.docsy.dev/) theme.

**Comment by xoxys** [comment]
I'm currently using `pdoc` now with a custom mako template. While this is also not a perfect solution it is really flexible. Maybe you should think about a full template support. Adding a Hugo specific support looks hard and everybody has different requirements to a hugo-like markdown files (e.g. custom front matter for themes). So I guess adding a generic template solution would be the best option. And to be honest, mako feels horrible and I would prefer jinja2 :)

**Comment by NiklasRosenstein** [comment]
There is already a `mkdocs` renderer, I don't see why there couldn't be a `hugo` renderer!

However I am fairly unfamiliar with Hugo. Do you have some examples of what would need to be rendered differently / what the front matter would look like? Would you be willing to contribute to the `hugo` renderer?

Regarding your mention of Jinja templates: That could indeed offer a lot of flexibility. We could also think about adding a `jinja` renderer 🙂

**Comment by NiklasRosenstein** [comment]
Actually let me ask for clarification first: Which version of Pydoc-markdown are you currently using? The one from the `develop` branch or 2.x from PyPI?

**Comment by genebean** [comment]
I’m using v3 and would be happy to contribute. https://gohugo.io/content-management/front-matter#front-matter-variables has some good info. If you stick to the basics of adding it in yaml format with title, date, and the like it should also work for Jekyll https://jekyllrb.com/docs/front-matter/

**Comment by NiklasRosenstein** [comment]
@genebean Sounds easy enough! I did some work towards not treating the `MkdocsRenderer` as a special child.

* Introduced a new `Server` interface that can be implemented by the new `HugoRenderer` to support calling `hugo server` when `--watch-and-serve` is passed to Pydoc-Markdown 
* Moved the `Page` config class from the `mkdocs` module to `pydoc_markdown.util.pages` so it can be re-used by the `HugoRenderer`

https://github.com/NiklasRosenstein/pydoc-markdown/compare/fbe72fd1b56fd2d86e4a9954a84e34b0e3d9fd01..2b925ce3bb83eb1bf8e6e3ce152929f5665001ff#diff-8c9e2b6c61db23c287efce31241f7376
