### ISSUE TITLE
Class level attributes with type hints don't render

### ISSUE THREAD

**Issue by epwalsh** [NiklasRosenstein/pydoc-markdown#115]
Hi,

I just noticed that class-level attributes with type hints aren't rendering, even after updating to the latest commit.

For example:

    $ cat <<EOF >a.py
      class SomeClass:
          """
          Docstring.
          """
      
          some_class_level_var: int = 1
          """
          This is a class-level var.
          """
    EOF
    $ pydoc-markdown -m a -I .

<details><summary>Show output</summary>

---

<a name=".a"></a>
# a

<a name=".a.SomeClass"></a>
## SomeClass Objects

```python
class SomeClass()
```

Docstring.

---

</details>

However, if you remove the type hint on `some_class_level_variable`:

<details><summary>Show output</summary>

---

<a name=".a"></a>
# a

<a name=".a.SomeClass"></a>
## SomeClass Objects

```python
class SomeClass()
```

Docstring.

<a name=".a.SomeClass.some_class_level_var"></a>
#### some\_class\_level\_var

This is a class-level var.

---

</details>

**Comment by NiklasRosenstein** [comment]
Hey @epwalsh , thanks for reporting this. Can you check out `develop` and see if it works for you now as expected? I'll release a new version when your response is positive.

**Comment by NiklasRosenstein** [comment]
Taking a quick peek at your `py2md.py` script, it looks like you're doing a lot of customization of the existing loader/filter/renderer. Do you feel like (some of) that functionality should be in Pydoc-Markdown? For common documentation use cases I'd like it to be usable with as little configuration as possible and ideally without any custom logic.

**Comment by NiklasRosenstein** [comment]
FYSA the current unreleased version changes the defaults to `MarkdownRenderer.descriptive_class_title` and `MarkdownRenderer.header_level_by_type`.

**Comment by epwalsh** [comment]
Thanks for the quick response @NiklasRosenstein! I just confirmed the fix worked. I'm not sure how much of our py2md script would be useful to others. It was an ad hoc solution to handle our very specific docstring conventions. But if there is something in there you think would be useful let me know, or feel free to just take it.

Best,
Pete
