### ISSUE TITLE
Links to github repo code

### ISSUE THREAD

**Issue by jsbroks** [NiklasRosenstein/pydoc-markdown#122]
I would like to add a source hyperlink to each function/method and class which redirects the user to the source code on Github.

If this isn't a feature you are interested in adding, how would I create my own render to add this?

Thanks!

**Comment by NiklasRosenstein** [comment]
Hey @jsbroks , I think this is a sensible feature to have in the `MarkdownRenderer`. We could add a `source_linker` option that defines how API objects are resolve into a link.

```yml
renderer:
  type: markdown
  source_linker: {type: github, repo: NiklasRosenstein/pydoc-markdown}
```

The source linker would then do something like

```py
@implements(SourceLinker)
class GitHubSourceLinker:
  repo = Field(str)
  def get_source_url(obj: docspec.ApiObject) -> str:
    sha = subprocess.getoutput('git rev-parse HEAD').strip()
    git_repo_path = ... # TODO
    relative_filename = os.path.relpath(obj.location.filename, git_repo_path)
    return 'https://github.com/{}/blob/{}/{}'.format(self.repo, sha, relative_filename)
```

And the Markdown renderer can use it like this

```py
if self.source_linker:
  fp.write('[[source]]({})'.format(self.source_linker.get_source_url(obj)
```

What do you think? Would you feel comfortable contributing this feature?

**Comment by jsbroks** [comment]
That sounds good, and I can help out
