### ISSUE TITLE
custom plugins support without setup: resolve by FQN

### ISSUE THREAD

**Issue by casperdcl** [NiklasRosenstein/pydoc-markdown#131]
From https://github.com/NiklasRosenstein/pydoc-markdown/issues/70#issuecomment-658705072:

> Currently all plugins need to be registered as a Python entrypoint.
> 
> Afaik entrypoints can only be registered via a setup script. If that doesn't fit in your workflow now, we could maybe add a command-line option or additionally support resolving plugins by their FQN additionally to the entrypoint name. Please do open a new issue in that case though :)

While this approch is occasionally seen in other projects, I personally view "using `setup.py` as a plugin/extension interface" to be a hack rather than an API.

**Comment by NiklasRosenstein** [comment]
Hey @casperdcl can you give it a try from the `develop` branch? You may still need to set `PYTHONPATH` if your custom class can not be otherwise imported.

**Comment by casperdcl** [comment]
yes works
