### ISSUE TITLE
broken link in documentation leads to 404

### ISSUE THREAD

**Issue by hkennyv** [NiklasRosenstein/pydoc-markdown#143]
Steps to reproduce:

* go to link - https://pydoc-markdown.readthedocs.io/en/latest/docs/getting-started/
* click `Configuration` link (leads to https://pydoc-markdown.readthedocs.io/en/latest/docs/getting-started/configuration, which is incorrect)

I believe it has something to do with the link ending with the `/`

**Comment by NiklasRosenstein** [comment]
Thanks :)
