### ISSUE TITLE
Feature proposal: Docusaurus renderer

### ISSUE THREAD

**Issue by m-vdb** [NiklasRosenstein/pydoc-markdown#147]
Hello @NiklasRosenstein !

Thanks a lot for this package, it's very helpful to us. We've recently setup [Docusaurus v2](https://v2.docusaurus.io/docs/) for our documentation website and we've forked this repository to create a Docusaurus renderer. I wonder if you would be interested in merging the code back to this repository. Here is the PR I worked on: https://github.com/RasaHQ/pydoc-markdown/pull/1

LMK, thanks!

**Comment by NiklasRosenstein** [comment]
Hey @m-vdb, that sounds great, I would welcome a PR :) I left a comment on the PR you linked, maybe you can look at that before proposing the feature as a PR!

Cheers,

**Comment by m-vdb** [comment]
Great 💯 I'll try to submit a PR then

**Comment by hkennyv** [comment]
+1 would love to see this feature! i'd love to help if i can as well

**Comment by m-vdb** [comment]
PR is ready for review here: https://github.com/NiklasRosenstein/pydoc-markdown/pull/151
