### ISSUE TITLE
Support specifying an alternative port

### ISSUE THREAD

**Issue by aersam** [NiklasRosenstein/pydoc-markdown#148]
Hi there

Thanks for this great project, its really awesome!

I'd like to run multiple instances of it at a given time, but I cannot do so easily as I cannot specify a port. I can tweak [mkdocs.py](https://github.com/NiklasRosenstein/pydoc-markdown/blob/develop/pydoc-markdown/src/pydoc_markdown/contrib/renderers/mkdocs.py#L173), by overriding get_server_url and passing --dev-addr to mkdocs. in start_server 

Is it easily possible to support passing a port?

**Comment by NiklasRosenstein** [comment]
Hey @aersamkull , I think it would be the easiest to support this as an environment variable.

    $ MKDOCS_PORT=8842 pydoc-markdown -so

**Comment by aersam** [comment]
Environment variable is fine for me. Did you already release it?

**Comment by NiklasRosenstein** [comment]
It's in 3.4.0

**Comment by aersam** [comment]
Thanks, works :)
