### ISSUE TITLE
Sphinx type and rtype entry are not processed

### ISSUE THREAD

**Issue by benjello** [NiklasRosenstein/pydoc-markdown#157]
Thank you for this neat piece of software.

Is there a way to tell the sphinx processor to deal with `:type :` and `:rtype :` entries like those presents in [here](https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html) ?

**Comment by NiklasRosenstein** [comment]
Hey @benjello ,

The right place to handle these entries would be in [SphinxProcesssor](https://github.com/NiklasRosenstein/pydoc-markdown/blob/cf625058dc1ab443a63e7e9abbbdf84dd39969b6/pydoc-markdown/src/pydoc_markdown/contrib/processors/sphinx.py#L40). How would you have that parameter be rendered as Markdown?

**Comment by m-birke** [comment]
Hi Niklas,

I just stumbled across this too.  I would propose to do it similar to sphinx.

Sphinx docstring style is the following:
:param [ParamName]: [ParamDescription](, defaults to [DefaultParamVal])
:type [ParamName]: [ParamType](, optional)

... becomes to

* [ParamName] ([ParamType]) - [ParamDescription]
OR
* [ParamName] ([ParamType], optional) - [ParamDescription]

(the ", defaults to ... " is just appended as it is, so this needs no care)

In Markdown you could do just the same, like:

- `metadata` (dict, optional): additional metadata to describe the object

:return: [ReturnDescription]
:rtype: [ReturnType]

becomes to

**Returns:** [ReturnDescription]
**Return type:** [ReturnType]

Like this or just

**Returns** ([ReturnType]): description... 

like

**Returns** (dict): description... 

would be great in my opinion :)

source: https://dev.to/zenulabidin/sphinx-docstring-best-practices-2fca

**Comment by NiklasRosenstein** [comment]
Hey @suitre77 , I like what you're proposing:

> Returns ([ReturnType]): description...

This will just need some work in the `SphinxProcessor` to understand content from multiple lines and summarize it into a single line. Not sure when I'll get to it, but it's high up on my list.

**Comment by NiklasRosenstein** [comment]
Heym @suitre77, I made it so that the following docstring:

```
  :param foo: A foo value
  :type foo: str
  :type bar: int
  :param bar: A bar value
  :returns: Some eggs from foo and bar
  :rtype: str
```

is rendered as

>  **Arguments**:
>
>  - `foo` (`str`): A foo value
>  - `bar` (`int`): A bar value
>
>  **Returns**:
>
>  `str`: Some eggs from foo and bar

**Comment by NiklasRosenstein** [comment]
v3.12.0

**Comment by m-birke** [comment]
appreciating, thanks :)
