### ISSUE TITLE
feature request: jinja2 renderer

### ISSUE THREAD

**Issue by nnnewb** [NiklasRosenstein/pydoc-markdown#175]
https://github.com/NiklasRosenstein/pydoc-markdown/blob/e7888af48d99287d70e89b51a09fc8d8d702d3cd/pydoc-markdown/src/pydoc_markdown/contrib/renderers/markdown.py#L199-L216

after looking into source code of markdown renderer, I start thinking is there any better way to implement an complex document, then jinja2 comes out my mind.

more customizability, clean and readable.

**Comment by nnnewb** [comment]
never mind

**Comment by NiklasRosenstein** [comment]
What had you change your mind @nnnewb ? A Jinja renderer may be quite useful indeed.
