### ISSUE TITLE
error in Docusaurus guide

### ISSUE THREAD

**Issue by Benedict-Carling** [NiklasRosenstein/pydoc-markdown#177]
In the page: https://github.com/NiklasRosenstein/pydoc-markdown/tree/develop/examples/docusaurus

It says to use the line in sidebar.js
```javascript
module.exports = {
  someSidebar: {
    "API Documentation": require("./docs/reference/sidebar.json"),
    Docusaurus: ['doc1', 'doc2', 'doc3'],
    Features: ['mdx'],
  },
};
```
However in your code you used
```javascript
module.exports = {
  someSidebar: {
    "API Documentation": [
      require("./docs/reference/sidebar.json")
    ],
    Docusaurus: ['doc1', 'doc2', 'doc3'],
    Features: ['mdx'],
  },
};
```

Only the latter works, it would be useful for others to update the guide to stop making the same mistake.

Best,
Benedict

**Comment by NiklasRosenstein** [comment]
Hey @Benedict-Carling , thanks for the info. Fixed in 25e9511bf9b8e96caf589f62817445e8c0f6ccef :)
