### ISSUE TITLE
pydoc-markdown style undocumented

### ISSUE THREAD

**Issue by kthy** [NiklasRosenstein/pydoc-markdown#185]
The docs state that pydoc-markdown

> Understands multiple doc styles (Sphinx, Google, Pydoc-Markdown)

However, I am unable to find a reference anywhere to what Pydoc-Markdown docstring style looks like. Halp?

**Comment by NiklasRosenstein** [comment]
Hey @kthy, there's an example in the docs here: https://pydoc-markdown.readthedocs.io/en/latest/docs/api-documentation/processors/#pydocmdprocessor-objects

While looking for it, I found there is a small typo in the example (the railing colon after "Raises" messes up the formatting). Fixed it in d74efe7
