### ISSUE TITLE
Feature request: allow configuration in pyproject.toml

### ISSUE THREAD

**Issue by kthy** [NiklasRosenstein/pydoc-markdown#186]
It would be awesome 🎉🥳 if Pydoc-Markdown could read its configuration from a `[tool.pydoc-markdown]` table in `pyproject.toml` so I don't have to litter my project directory with yet another config file.

**Comment by NiklasRosenstein** [comment]
Hey @kthy, I like the idea. The configuration docs contains an example for defining the config in `pyproject.toml`: https://github.com/NiklasRosenstein/pydoc-markdown/blob/develop/docs/configuration.md

Will be available in the next release!
