### ISSUE TITLE
mkdocs dep incompatibilty of newest versions 

### ISSUE THREAD

**Issue by m-birke** [NiklasRosenstein/pydoc-markdown#188]
mkdocs 1.2 requires watchdog>=2.0
pydoc-markdown 3.13.0 requires watchdog<2.0.0,>=1.0.0

it seems to work anyway, but using tox causes problems, when tox first installs mkdocs and afterwards pydoc-markdown within its virtualenv

**Comment by NiklasRosenstein** [comment]
Hey @suitre77 ,

later versions of Pydoc-Markdown depend on `watchdog` without version constraints.
