### ISSUE TITLE
docusaurus example: update dependencies/configs?

### ISSUE THREAD

**Issue by tony** [NiklasRosenstein/pydoc-markdown#189]
Is it possible the example can be updated to work with docusaurus v2 beta?

**Comment by NiklasRosenstein** [comment]
Hey @tony, would you mind filing a PR for that? 🙂

**Comment by tony** [comment]
@NiklasRosenstein Possibly this weekend.  If anyone reading this gets to it before I do please feel free to PR as well

TLDR: I'm not using docusaurus for any python projects yet.  I have a PR where i'm trying pydoc-markdown here but haven't touched it in a few months: https://github.com/vcs-python/libvcs/pull/275 (sphinx -> docusaurus)
