### ISSUE TITLE
Ignore # in code blocks

### ISSUE THREAD

**Issue by keunwoochoi** [NiklasRosenstein/pydoc-markdown#19]
Seems like the current markdown parser is interpreting symbols like `#` as markdown symbol even if it is within code blocks ```. I assume it is not an expected behaviour.

**Comment by NiklasRosenstein** [comment]
Hm at least on the current tip, I can not confirm this behaviour. I've added a `testmodule` directory that can be used to test pydocmd during development:

    def mycoolfunction(samplesize, width=32, **options):
      """
      This is a pretty cool function.

      # Arguments
      samplesize (int): Test sample size.
      width (int): The width.
      options: Additional options

      # Example
      ```python
      # This is a very simple example.
      mycoolfunction(samplesize, width, **options)
      ```

      See also: #myothercoolfunction().
      """

      pass


    def myothercoolfunction(prettycool):
      """
      Don't you think?
      """

      pass
      
Gives me:

----

<h1 id="test">test</h1>

<h2 id="test.myothercoolfunction">myothercoolfunction</h2>

```python
myothercoolfunction(prettycool)
```

Don't you think?

<h2 id="test.mycoolfunction">mycoolfunction</h2>

```python
mycoolfunction(samplesize, width=32, **options)
```

This is a pretty cool function.

__Arguments__

- __samplesize (int)__: Test sample size.
- __width (int)__: The width.
- __options__: Additional options

__Example__

```python
# This is a very simple example.
mycoolfunction(samplesize, width, **options)
```

See also: `myothercoolfunction()`.

**Comment by cbsteh** [comment]
The Python code block (lines 12-15 in ```testmodule```) fails when the first line of the docstring is on the same line as the opening triple quotes, such as:
```
# Fails
def mycoolfunction(samplesize, width=32, **options):
  """This is a pretty cool function.
```
But this works:
```
# OK
def mycoolfunction(samplesize, width=32, **options):
  """
  This is a pretty cool function.
```

**Comment by gabrieldemarmiesse** [comment]
It seems this also occurs when using urls with anchors. See #44 .

**Comment by NiklasRosenstein** [comment]
@cbsteh Tbh not sure when but I think this has been fixed at some point. Been some time 😅 

`````python
def function_with_docstring_on_same_line():
  """This is a pretty cool function.

  # Arguments
  None actually.

  # Example
  ```python
  # This is a very simple example.
  mycoolfunction(samplesize, width, **options)
  ```

  See also: #function_without_docstrings().
  """
`````

Gives

<details>

<h2 id="testmodule.function_with_docstring_on_same_line">function_with_docstring_on_same_line</h2>

```python
function_with_docstring_on_same_line()
```
This is a pretty cool function.

__Arguments__

None actually.

__Example__

```python
# This is a very simple example.
mycoolfunction(samplesize, width, **options)
```

See also: `function_without_docstrings()`.

</details>

---

@gabrieldemarmiesse #44 is unrelated to this issue. :-) # in URLs must be treated differently from # in code blocks.
