### ISSUE TITLE
Option to remove vertical bar '|' before method definition in code block ?

### ISSUE THREAD

**Issue by t6847kimo** [NiklasRosenstein/pydoc-markdown#190]
Hi, I have noticed that there is '|' before each method definition, which is a little annoying for me.
For example,

```
 | @property
 | def foo() -> bool
```

Is it possible to remove it by any option?

**Comment by NiklasRosenstein** [comment]
Hi @t6847kimo , not as of right now. Would you like to contribute an option to the MarkdownRenderer to disable it?

https://github.com/NiklasRosenstein/pydoc-markdown/blob/bcd35748619a218f5fdfe565d29b7674ecae4faa/pydoc-markdown/src/pydoc_markdown/contrib/renderers/markdown.py#L257-L258

**Comment by t6847kimo** [comment]
OK. I could give it a try.

**Comment by NiklasRosenstein** [comment]
Closing as the PR was merged. :)
