### ISSUE TITLE
Render Markdown Directly

### ISSUE THREAD

**Issue by reskin89** [NiklasRosenstein/pydoc-markdown#191]
This may not be an issue, but I can't seem to figure out a way to just render Markdown files based on docstrings? It looks like I have to create the pydoc-markdown.yml and use mkdocs to just generate MD files.  Is this accurate?

**Comment by NiklasRosenstein** [comment]
Hey @reskin89 , you can actually specify a YAML config on the command-line as the first argument. You can also rely on the default config and amend it by various command-line flags. For example:

    $ pydoc-markdown '{ renderer: { type: markdown } }' -I ./src -m mymodule

(Note that `markdown` is already the default renderer so the above config is actually superfluous).

**Comment by NiklasRosenstein** [comment]
Closing due to no response.
