### ISSUE TITLE
SphinxProcess does not support multi-line parameter docstrings

### ISSUE THREAD

**Issue by NiklasRosenstein** [NiklasRosenstein/pydoc-markdown#195]
![image](https://user-images.githubusercontent.com/1318438/126665156-8d4dfe58-1dbb-4960-9554-5e2ee9f5ea3d.png)
![image](https://user-images.githubusercontent.com/1318438/126665241-3c97e836-a90f-48a3-bf5d-86d0225555a4.png)

**Comment by timcharper** [comment]
@NiklasRosenstein have you done any work on this? I was thinking the parser could be improved by having a pre-processor that splits the docstring in to contiguous chunks, where each chunk is defined as the subsequent lines being indented. Then, when the text chunk is checked for :param:, we're checking a chunk of text and not a line, so the whole chunk can be used as the param doc.

**Comment by NiklasRosenstein** [comment]
Hi @timcharper , I haven't. What you are suggesting sounds sane, would you like to make a contribution? 🙂

**Comment by gmarks2149** [comment]
I've created a potential fix for this issue in #223 I'm not sure if that's a direction you want to go or not. I'm open to feedback.
