### ISSUE TITLE
Showing arguments in __init__() 

### ISSUE THREAD

**Issue by keunwoochoi** [NiklasRosenstein/pydoc-markdown#20]
The Keras documentation is showing default values under each class, probably by getting from its `__init__` method, but pydocmd doesn't seem to (my html does not). Am I doing something wrong or is it how it's supposed to work now?

**Comment by keunwoochoi** [comment]
Sorry for issue storms, but I think these should be dealt with separately ;)

**Comment by NiklasRosenstein** [comment]
Don't worry, and thanks for the feedback. :)

It is certainly a good idea to show the default values in the method description.

**Comment by NiklasRosenstein** [comment]
Have you been using Python 2? Then this issue is likely related to #21 and fixed with it. Please confirm

**Comment by keunwoochoi** [comment]
Yes I am. Will try it soon, thanks!

**Comment by NiklasRosenstein** [comment]
Fixed with #21.
