### ISSUE TITLE
How to avoid the HTML escape characters in the code blocks?

### ISSUE THREAD

**Issue by skzhang1** [NiklasRosenstein/pydoc-markdown#226]
**Environment**

- Pydoc-Markdown Version: 4.3.2
- Python Version: v3.7
- Operating System:  macOS

**Describe the bug**
I want to generate the code block from the annotations. 

````
class cool_class():
    """cool!"""

    def __init__(
        self,
        cool_member
    ):
        """
        # Arguments
            cool_member: a cool guy

            ```python
                print("cool!")
            ```
    
        """
    def cool_function(self):
        print("cool!")
````

But the markdown file I generate is
````
```python
class cool_class()
```

cool!

#### \_\_init\_\_

```python
def __init__(cool_member)
```

__Arguments__

- __cool_member__: a cool guy

    ```python
        print(&quot;cool!&quot;)
    ```

````
My config is 

````
loaders:
   - type: python
     search_path: [../cool/]
     ignore_when_discovered: [cool1,cool2]
processors:
  - type: filter
    skip_empty_modules: true
  - type: smart
  - type: crossref
renderer:
  type: docusaurus
  docs_base_path: docs
  relative_output_path: reference
  relative_sidebar_path: sidebar.json
  sidebar_top_level_label: Reference
````
**Expected behavior**

Replace &quot with ". I do not need any escape characters.

Look forward to your reply.
Thanks!

**Comment by NiklasRosenstein** [comment]
Hello @Shao-kun-Zhang ,

Have you tried turning off the `escape_html_in_docstring` option that is enabled by default for the Markdown renderer used in the Docusaraus renderer?

https://github.com/NiklasRosenstein/pydoc-markdown/blob/f8436b3df0445f342b2f745ebe7ea379d66a5150/src/pydoc_markdown/contrib/renderers/docusaurus.py#L28

That would go

```yaml
renderer:
  type: docusaurus
  # ...
  markdown:
    escape_html_in_docstring: false
```

Let me know if that works for you!

**Comment by skzhang1** [comment]
It works! Thanks for your help! I am very appreciate it. (I remember I have tried before, but it didn't work before. @NiklasRosenstein
