### ISSUE TITLE
PyPI Package Publish action is failing

### ISSUE THREAD

**Issue by calebho** [NiklasRosenstein/pydoc-markdown#234]
**Environment**

n/a

**Describe the bug**

[It seems like the publish workflow is failing](https://github.com/NiklasRosenstein/pydoc-markdown/runs/4497902647?check_suite_focus=true). As a result, the latest version available on PyPI is 4.3.2 while the latest tag is 4.5.0

**Expected behavior**

The latest package version should be published to PyPI when a new tag is pushed

**Comment by calebho** [comment]
Current workaround is to install from GitHub using pip's VCS integration

**Comment by NiklasRosenstein** [comment]
Thanks for the heads up @calebho, seems like the PyPI tokens expired. Fixed it, now 4.4.0 and 4.5.0 are available on PyPI.

Cheers,
Niklas
