### ISSUE TITLE
Text is incorrectly rendered as code

### ISSUE THREAD

**Issue by rahiel** [NiklasRosenstein/pydoc-markdown#25]
With the function:
```python
def add(a, b):
    """Add two numbers.

    # Arguments

    a (int): First number
    b (int): Second number

    # Example

    This text is rendered as code :(
    """
    return a + b
```

I get as output:
<h2 id="code.add">add</h2>

<pre><code class="python">add(a, b)
</code></pre>

<p>Add two numbers.</p>
<p><strong>Arguments</strong></p>
<ul>
<li><strong>a (int)</strong>: First number</li>
<li><strong>b (int)</strong>: Second number</li>
</ul>
<p><strong>Example</strong></p>
<pre><code>This text is rendered as code :(
</code></pre>
              
-----
This renders correctly if in the above the docstring starts on a new line, so like:
```python
def add(a, b):
    """
    Add two numbers.
    ...
```

However, starting the text immediately after the opening `"""` (like in the first version of `add`) is [python convention](https://www.python.org/dev/peps/pep-0257/#multi-line-docstrings).

**Comment by NiklasRosenstein** [comment]
I'm not sure where this is coming from. Looking at your example, it seems that only the code following the `# Example` section is rendered as code. I'll look into it tomorrow.

**Comment by NiklasRosenstein** [comment]
`textwrap.dedent()` is not sufficient for Python docstrings. Added a `trim()` function in `pydocmd.loader` that does the job.
