### ISSUE TITLE
Poetry cant install with latest typing-extenstion

### ISSUE THREAD

**Issue by nrbnlulu** [NiklasRosenstein/pydoc-markdown#267]
**Environment**
Any.

- Pydoc-Markdown Version: 4.6.3 
- Python Version: Any
- Operating System:  Any

```console
databind.json (>=1.5.2,<2.0.0) requires typing-extensions (>=3.10.0,<4.0.0).
  Thus, pydoc-markdown (>=4.6.3,<5.0.0) requires typing-extensions (>=3.10.0,<4.0.0).
  So, because strawberry-django-plus depends on both typing-extensions (>= 4.1.0) and pydoc-markdown (^4.6.3), version solving failed.
```

installing this package with typing-extenstions<=4.1.0 results poetry error.

**Expected behavior**

Clear installation

**Comment by NiklasRosenstein** [comment]
Hi @nrbnlulu , I prepped a version of databind that accepts higher versions of `typing-extensions`; unfortunately I'm blocked to release because of https://github.com/python-poetry/poetry/issues/5782#issuecomment-1173574340

**Comment by nrbnlulu** [comment]
Cool! thanks, great job!

**Comment by NiklasRosenstein** [comment]
Hey @nrbnlulu I managed to get the release published. Can you try again?

**Comment by nrbnlulu** [comment]
Working! :100:
