### ISSUE TITLE
How to igonre module imports

### ISSUE THREAD

**Issue by nrbnlulu** [NiklasRosenstein/pydoc-markdown#269]
### Discussed in https://github.com/NiklasRosenstein/pydoc-markdown/discussions/263

<div type='discussions-op-text'>

<sup>Originally posted by **nrbnlulu** May 26, 2022</sup>
Currently generating docs for one module like this

```py
    context = Context(directory=root_dir)
    loader = PythonLoader(search_path=['gqlauth'], modules=['decorators'])
    renderer = MarkdownRenderer(render_module_header=False,)

    loader.init(context)
    renderer.init(context)
    header = """
# Decorates

---

    """
    modules = loader.load()
    with open(root_dir / 'docs' / 'decorators.md', 'w+') as f:
        f.write(header + renderer.render_to_string(modules))

```

this is the result:

![image](https://user-images.githubusercontent.com/88795475/170564425-12fcadb8-2219-4da0-ae8b-0d8461ca1460.png)

I want only the functions or classes how can I remove the import statements?
</div>

**Comment by NiklasRosenstein** [comment]
Closing in favour of the discussion.
