### ISSUE TITLE
In-document anchor link is incorrectly parsed as symbol

### ISSUE THREAD

**Issue by liu2g** [NiklasRosenstein/pydoc-markdown#274]
**Environment**

- Pydoc-Markdown Version: v4.6.0
- Python Version: v3.7.4
- Operating System: Windows 10

**Describe the bug**

This is somehow related to #44, but in my particular use case, I would like to link to an anchor in the same document manually. Since the anchor is in the same document, it starts with `#` right away without `/`.

The context is to generate a markdown page then later append a custom block of text into the same file, such that they appear as one whole article in a wiki.

For example, if my module is `mymodule` and I have more text to dump at the end, I would do

```bash
pydoc-markdown -m mymodule > wikipage.md && cat more-text.md >> wikipage.md
```

In `mymodule.py`, there is

```python
def foo():
    """
    Refer to [flowchart](#flowchart-of-foo)
    """
```

and in `more-text.md`, there is 

```md
# Flowchart of Foo
Here is a flowchart of foo
```

However, it generates below in the `wikipage.md`

```md
Refer to [flowchart](`flowchart`-of-foo)
```

**Expected behavior**

The anchor should be correctly parsed such that `[flowchart](#flowchart-of-foo)` stays the same in the rendered markdown document

**Comment by NiklasRosenstein** [comment]
Thanks for reporting this issue @liu2z2 . Should be fixed in 614d076fb3d3130b99c80e96218fcfd95f6c0926
