### ISSUE TITLE
:param: function arguments on one line

### ISSUE THREAD

**Issue by Tagar** [NiklasRosenstein/pydoc-markdown#28]
Please have a look at result of 
```shell
pydocmd simple abalon.spark.sparkutils+ > README.md
```
and result rendered at 
https://github.com/Tagar/abalon

- notice :param: arguments are all together. 
It would be great if they are split at least to separate lines.

**Comment by NiklasRosenstein** [comment]
That's not how parameters are being documented with pydoc-markdown. Instead of 

```python
def sparkutils_init (i_spark, i_debug=False):
    '''
    Initialize module-level variables

    :param i_spark: an object of pyspark.sql.session.SparkSession
    :param i_debug: debug output of the below functions?
    '''
```

it would need to be

```python
def sparkutils_init (i_spark, i_debug=False):
    '''
    Initialize module-level variables

    # Parameters
    i_spark: an object of pyspark.sql.session.SparkSession
    i_debug: debug output of the below functions?
    '''
```

The issue about converting Sphinx syntax is still open, see #1

**Comment by Tagar** [comment]
Thanks for prompt response @NiklasRosenstein 
That's good to know it's already beeing tracked.
Yes, we use Sphinx syntax.
