### ISSUE TITLE
Your home page is broken

### ISSUE THREAD

**Issue by TomiBelan** [NiklasRosenstein/pydoc-markdown#303]
![image](https://github.com/NiklasRosenstein/pydoc-markdown/assets/1022278/69e75151-9291-4f33-b7fa-abf6c55070cd)

Your documentation site https://niklasrosenstein.github.io/pydoc-markdown/ just says `@cat ../../readme.md :with slice_lines = "2:"`. Not a great first impression.

**Comment by TomiBelan** [comment]
Thanks for fixing it.

**Comment by NiklasRosenstein** [comment]
Thanks for reporting it 👍
