### ISSUE TITLE
Release 2.0.2?

### ISSUE THREAD

**Issue by rahiel** [NiklasRosenstein/pydoc-markdown#34]
I saw some old issues (#25 and #26 ) reappear in my generated documentation. I was confused, but I forgot that I had to use `pydoc-markdown` from the git repo instead of the pypi release.

Could you release a new version?

Thanks for your work again!

**Comment by NiklasRosenstein** [comment]
Thanks for the reminder &ndash; 2.0.2 is on PyPI (https://pypi.python.org/pypi/pydoc-markdown/2.0.2)
