### ISSUE TITLE
Mangles typing.NewType 

### ISSUE THREAD

**Issue by sda-amfam** [NiklasRosenstein/pydoc-markdown#35]
If I have an argument to a function that is a custom type using the new Python 3 type annotations, e.g.

```python
from typing import NewType
NodeID = NewType('NodeID', str)
```

Currently, `pydoc-markdown` mangles this:
```python
class GraphDriver:
    def get_node(self, node_id: NodeID):
      """ method """
```
to:
`GraphDriver.get_node(self, node_id:<function NewType.<locals>.new_type at 0x1023bb7b8>) `

Instead of:

`GraphDriver.get_node(self, node_id:NodeID)`
or
`GraphDriver.get_node(self, node_id:<module_name>.types.NodeID)`

I keep my custom types in `<module_name>.types` so the latter would be my desired behavior.  Is there a way to disable this behavior, or should it be special-cased?

**Comment by NiklasRosenstein** [comment]
Hi @sda-amfam, sorry for the late reply. This would need to be handled separately in `pydocmd.loader.PythonLoader.load_section()`.

**Comment by NiklasRosenstein** [comment]
This is auto-magically resolved in v3 due to the way code is parsed (with `lib2to3`).
