### ISSUE TITLE
no break line between parameters

### ISSUE THREAD

**Issue by shaidams64** [NiklasRosenstein/pydoc-markdown#37]
I'm not getting any line breaks between my parameter lines, Does any one know what's causing it? I see all parameters in one line even though I have colon for each one in the documentation:

`""" Calls Prophet cross_validation function with passed horizon, initial and
	period values and returns all across validated error metrics

	# Parameters:
	model (Prophet obj): Prophet class object,Fitted Prophet model.
	horizon (int): orecast horizon in days .
	period (int):  Simulated forecast will be done at every this period. 
		If not provided, 0.5 * horizon is used.
	initial (int): numberof days. The first training
    	period will begin here. If not provided, 3 * horizon is used.

    # Returns:
    (pd.Dictionary) : A dictionary of cross validation error metrics
    """`

This is what's generated :
Thanks a lot in advance!
<img width="754" alt="screen shot 2018-04-06 at 4 40 03 pm" src="https://user-images.githubusercontent.com/13664507/38448474-35f3801a-39b9-11e8-8d8d-301205196902.png">

**Comment by shaidams64** [comment]
So adding <br> at the end of each line fixed the issue, but is this the way it's supposed to be? also for some reason "Return" does not get marked down and shows up as " #Returns : ...", can you think of a reason for that? thanks

**Comment by NiklasRosenstein** [comment]
As I noted in #36, there should be no trailing double-colon in the section header (here `# Parameters:`).
