### ISSUE TITLE
__init__ Documentation Missing

### ISSUE THREAD

**Issue by jsmith** [NiklasRosenstein/pydoc-markdown#45]
Currently, it seems like the class docstring is used in place of the `__init__` docstring. Could this be a configurable setting? I would like to put the class documentation right below the class header and the `__init__` documentation under the constructor.

**Example**  
Input:
```python
class Class:
    """
    The class documentation!
    """

    def __init__(self, param):
        """
        The constructor.

        :param param: A parameter.
        """
        self.param = param
```
Output:
![image](https://user-images.githubusercontent.com/18077531/40544724-b05bb6a8-5fff-11e8-807b-eeeb89a68efc.png)

**Comment by NiklasRosenstein** [comment]
Maybe then we should instead always treat `__init__` like any other method. 

For example, I would prefer this

># Class
>
>The class documentation!
>
>## Class.\_\_init\_\_()
>
>     Class.__init__(self, param)
>
>The constructor
>
>__Parameters__
>* param: A parameter.

over this

># Class
>
>The class documentation!
>
>     Class(self, param)
>
>The constructor
>
>__Parameters__
>* param: A parameter.

**Comment by jacsmith21** [comment]
Yeah, that makes sense to me. I prefer this way as well!

**Comment by florimondmanca** [comment]
I believe there is a more general aspect to it, being that "dunder" methods (`__init__`, `__call__`, `__add__`, etc) are ignored even though they have a docstring. I imagine this comes from Pydoc-Markdown ignoring any function that starts with an underscore or similar, but oftentimes dunder methods are particularly useful to document.

**Comment by eode** [comment]
I've only thought of two ways that really work to handle a class + `__init__` docstrings, but pydoc-markdown doesn't do either, yet:

* As with python help(Foo):
  * Don't use the initialization signature for Foo, use `Foo.mro()[1:]`, `Foo.__bases__`, or equivalent
  * Treat `__init__` as any other method, including the initialization signature
* As in some other documentation tools:
  * Use the `__init__` signature for Foo (as you do now)
  * Possibly append the MRO or bases
  * Append `__init__`'s docstring to Foo's docstring.

..any other ideas?

**Comment by eode** [comment]
@florimondmanca I've thought about that, too -- there might be a need for some kind of inclusion/exclusion list.  In our own modification of pydoc-markdown, we have (if I remember correctly) an 'include' list that supercedes ignoring underprefix members.

However, there's also not currently a way to specify a class specific (otherwise-excluded) submembers -- might be something to consider long-term.

**Comment by NiklasRosenstein** [comment]
Hey all,

Pydoc-Markdown 3 generates the following output for @jsmith's example:

![image](https://user-images.githubusercontent.com/1318438/75629672-2767b300-5be4-11ea-8c5e-6a3baebc0859.png)

I believe this now matches the expectations and the behavior of the built-in `help()` function as described by @eode.

Closing this out 🙂
