### ISSUE TITLE
 Allow splitting docs into multiple files

### ISSUE THREAD

**Issue by NiklasRosenstein** [NiklasRosenstein/pydoc-markdown#5]
`pydoc-markdown` will currently generate a single markdown formatted text that is output to stdout. This is not practical for large packages. It should be possible to split the documentation into separate files per module/class (configurable).

Note that we need to generate appropriate relative cross-file links hat are interpreted correctly by the markdown parser. BitBucket and GitHub are quite different in that regards, and it also makes a difference whether the markdown is hosted on a GitHub Wiki or in the repository. This all needs to be configurable.

About links, see also #4

**Comment by NiklasRosenstein** [comment]
Since v2.0.0, we're generating separate pages for MkDocs, effectively resolving this issue.

**Comment by mrunderline** [comment]
Hi,
Dose this feature supported in the current latest version(3.9.0)?

**Comment by NiklasRosenstein** [comment]
Hi @mrunderline ,

Yes, there is currently a renderer for `Mkdocs`, `Hugo` and `Docusaurus` , each of which produces multiple Markdown files and the format and layout expected by the targeted tool.

Please check out the documentation https://pydoc-markdown.readthedocs.io/en/latest
