### ISSUE TITLE
"Pure" markdown headers instead of HTML tags

### ISSUE THREAD

**Issue by jaraen** [NiklasRosenstein/pydoc-markdown#58]
Hi! Thanks a lot for making pydoc, after many hours struggling with other tools this one fits pretty well my workflow in a very simply manner. However, I found pretty strange that some html headers `H1`, `H2`... are generated when using `pydocmd simple`, instead of markdown headers `#`, `##`... 

In our particular case, this avoids the theme we use to correctly build the table of content. Since creating .md files seems to be the main purpose of pydoc-markdown, I think html tags could be optional and only enabled on demand?

**Comment by NiklasRosenstein** [comment]
We should add an option to control the behaviour and decide on a default.

**Comment by DraTeots** [comment]
For me, as a first time user of the pydoc-markdown, it was a surprise to see html tags instead of markdown headers. Which actually lead to this issue.

**Comment by NiklasRosenstein** [comment]
This feature is implemented in https://github.com/NiklasRosenstein/pydoc-markdown/pull/55 (already merged). Will release a new version on PyPI later today.
