### ISSUE TITLE
Descriptors

### ISSUE THREAD

**Issue by AuHau** [NiklasRosenstein/pydoc-markdown#62]
I have a small framework in Django ORM's style which has entities classes that consist of fields. Fields are built as Python's descriptors. I want to use your tool for the entities doc generation, but the execution of the tool with a configuration which seems valid fails on ModuleNotFoundError.

After some debugging, it seems that the problems lay in Descriptors. Have you tried your solution with them? 
It seems to me, that problem is in [`import_object_with_scope`](https://github.com/NiklasRosenstein/pydoc-markdown/blob/master/pydocmd/imp.py#L69), where using `getattr(obj, part)` actually calls the descriptor's `__get__()` method instead of getting the descriptor's instance. This can be fixed in my code as is proposed for example in [this StackOverflow question](https://stackoverflow.com/questions/21629397/neat-way-to-get-descriptor-object), but I think your tool should incorporate a way which will overcome this on its own.

**Comment by AuHau** [comment]
After some more debugging in your code, I have come up with using `sub_obj = obj.__dict__[part]` instead of `sub_obj = getattr(obj, part)` which fixed the problem.

Do you see some short-coming with this solution? 
If not I will be happy to provide PR for that.

**Comment by NiklasRosenstein** [comment]
I think this change is sane, as long as `obj` actually has ` __dict__` member. Otherwise we should still use `getattr()`. You are welcome to create a PR. Can add the reasoning of this in a comment?

Can you provide a small sample of what kind of code you are trying to document? I'm working on a new version that no longer executes the Python code but parses it with `lib2to3` and would like to see how well it works with Django code.

**Comment by NiklasRosenstein** [comment]
Thanks for linking the example!

> Does for example Sphinx uses same approach?

AFAIK Sphinx also runs your code, so if you have any dependencies that you can't satisfy where your documentation is built, you need to provide a dummy module.

I do hope that it will be a much cleaner solution. Finding docstrings as used in your example (and similarly as described in #53 that you linked) like this

```
# This is a docstring.
abc = 'foo'
```

will be much easier. In fact, the code in [develop](https://github.com/NiklasRosenstein/pydoc-markdown/tree/develop) already supports this (not the trailing docstring though).
