### ISSUE TITLE
'pages' not in pydocmd.yml

### ISSUE THREAD

**Issue by AuHau** [NiklasRosenstein/pydoc-markdown#63]
I have my own `mkdocs.yml` which has a quite extensive configuration because of the theme and additional plugin. Because of this, I don't really want to specify all the 'pages' in `pydocmd.yml` as it will duplicate the information in `mkdocs.yml`. 

Unfortunately, without this option, the execution of your tool fails on `KeyError` at https://github.com/NiklasRosenstein/pydoc-markdown/blob/d8652bcb45a4cb603b4c67883776e0d8f2f9ec7c/pydocmd/__main__.py#L132. 

A simple check for the existence of the option should be sufficient. 
Can I make PR for it?

**Comment by NiklasRosenstein** [comment]
I'm not a 100% sure about the implications of not specifying pages in the pydocmd config, but you are welcome to give it a try, and if it works they way you need it, create a PR. :-)
