### ISSUE TITLE
lib2to3 the right way?

### ISSUE THREAD

**Issue by AuHau** [NiklasRosenstein/pydoc-markdown#68]
@NiklasRosenstein, I was looking at your develop version and it looks promising! My only concern would be the choice of `lib2to3`. Why did you decide to go with it? 
I mean, there are libraries for parsing AST out there, which primarily focuses on that job. There is one incorporated directly in Python: `ast` package.
I still do not completely understand your development code, so there might be other features you are using from the `lib2to3`...

My only worry, which I wanted to point out is that you are using `lib2to3` in a way which was not meant for it. As the documentation explicitly says: "The lib2to3 API should be considered unstable and may change drastically in the future.". I doubt there will be any big changes now, but I would be actually worried that this library won't be part of future Python 3 releases as the life-span of Python 2.7 is coming to an end very soon and it would be a pity to develop something which won't work in future...

What are your thoughts about this?

**Comment by NiklasRosenstein** [comment]
I am deliberately not using the `ast` module as it does not preserve comments.

There are actually a bunch of commonly used tools available that make use of `lib2to3` (eg. YAPF and Black). They (or we) will find a way if and when `lib2to3` support is dropped, or move to another tool once a good one comes around the corner.

**Comment by AuHau** [comment]
Yeah, I was thinking that it might be the case. 

Cool! Good to know! :-) 

I guess no need to leave this issue open...
