### ISSUE TITLE
Enums generate repeated comments for every element

### ISSUE THREAD

**Issue by jaraen** [NiklasRosenstein/pydoc-markdown#69]
Hi Niklas,

Given an enumeration class like 

```
class PetType(enum.Enum):
    """ Enumeration to identify possible pets
    """

    DOG = 0
    CAT = 1
    MOUSE = 2
```

Output from  `pydocmd` results in a class comment repeated for every element of the Enum.
 
```
## PetType
``python
PetType(self, /, *args, **kwargs)
``
Enumeration to identify possible pets

### CAT
Enumeration to identify possible pets

### DOG
Enumeration to identify possible pets

### MOUSE
Enumeration to identify possible pets
```

Is this the expected behavior? if so, what would be the right way to document Enums?

Thanks a lot

**Comment by NiklasRosenstein** [comment]
Hi @jaraen , no this isn't expected behaviour. My guess is that each enum value has a `__doc__` member inherited from the enum class. Maybe they need to be handled in a special way to prevent this behaviour.

**Comment by NiklasRosenstein** [comment]
This will not happen in Pydoc-markdown 3
