### ISSUE TITLE
Reload on config change

### ISSUE THREAD

**Issue by lgeiger** [NiklasRosenstein/pydoc-markdown#79]
It would be great if `pydocmd serve` would reload the when the config changes.
This would make the functionality on-par with `mkdocs serve`.

**Comment by NiklasRosenstein** [comment]
v3 has a `--watch-and-serve/-w` option that re-renders the Markdown files when any of the parsed Python source files changes. Subsequently, `mkdocs serve` will automatically re-render the HTML files,

I should note that currently it re-renders all Markdown files, not only the ones that would need to be re-rendered from the change. But I think that this should be tackled in another issue.
