### ISSUE TITLE
Adds trailing whitespaces to functions and blank spaces

### ISSUE THREAD

**Issue by walintonc** [NiklasRosenstein/pydoc-markdown#8]
I generated a markdown and the result is the following:

##### `get_pid(node, service)` 

> Uses systemctl to obtain the PID of a running service
> 
>    Return type is Integer.
>    Returns 0 for a service that does not exist or is not running.

Where after get_pid(node, service) there is a trailing whitespace
And in the blank-line after the description (PID of running a service) there is another one.

Please fix.

**Comment by NiklasRosenstein** [comment]
@walintonc You think you can create a Pull Request to fix this issue?

**Comment by walintonc** [comment]
Thank you.
