### ISSUE TITLE
Show parent class

### ISSUE THREAD

**Issue by iansan5653** [NiklasRosenstein/pydoc-markdown#83]
It would be nice to see the parent class(es) shown if a class inherits directly, ie:

```python
class MyError(RuntimeError):
    """Error raised when my thing happens."""
    pass
```
Currently, this outputs:

>## MyError
>```python
> MyError(self, /, *args, **kwargs)
> ```

This clearly has no clear way to show that `MyError` inherits from `RuntimeError`.

**Comment by NiklasRosenstein** [comment]
Hey @iansan5653,

I totally agree with you. I will implement this in v3.x
