### ISSUE TITLE
Set Table of Contents to be optional

### ISSUE THREAD

**Issue by davidban77** [NiklasRosenstein/pydoc-markdown#85]
Hello!, great project BTW!

Started using recently the develop version and was wondering if there is an option to disable the TOC generated. Main reason is because there are themes that provide the TOC already, so disabling it on the document generated it would make it less cluttered.

What do you think?

Thanks!

**Comment by NiklasRosenstein** [comment]
Hey @davidban77,

thanks, I'm glad you like it. :-) 

Currently you can't disable the TOC via the command-line, but you can in the `pydoc-markdown.yml` configuration file.

```yml
renderer:
  type: markdown
  render_toc: false
```

You can supply any of the options below in this section! 

https://github.com/NiklasRosenstein/pydoc-markdown/blob/468cace9378a64a267848c07c21a5aedbfab2cf3/src/pydoc_markdown/contrib/renderers/markdown.py#L35-L52

**Comment by davidban77** [comment]
Ah thanks! that is what I was looking for.

Great to see so many options :)
