### ISSUE TITLE
Add support for lazy type annotations

### ISSUE THREAD

**Issue by vemel** [NiklasRosenstein/pydoc-markdown#86]
Python 3.7+ supports lazy type annotations https://www.python.org/dev/peps/pep-0563/, but `inspect.signature` does not resolve lazy annotations for you and produces an ugly function signature

```python
from __future__ import annotations
from typing import Optional, Text

def greet(name: Optional[Text] = None) -> Text:
   return f'Hi, {name or "user"}'

# ugly annotation generated by PythonLoader
greet(name: 'Optional[Text]' = None) -> 'Text'

# nice annotations with resolved type hints and proper highlight
def greet(name: Union[str, Any] = None) -> str
```

This is how we can do it in `PythonLoader._get_function_signature` 

```python
        # do not convert signature to string
        signature = inspect.signature(function, follow_wrapped=True)

       # definition is used only for proper code highlight
        definition = 'def'
        if isclass:
            definition = 'class'

        # Resolve type hints and replace NoneType with None (optional)
        try:
            prettify = lambda x: x if x is not type(None) else None
            type_hints = {key: prettify(value) for key, value in get_type_hints(function).items()}
        except TypeError:
            type_hints = {}

        # Remove `self`, I believe user should not see it (optional)
        clean_parameters = {}
        for key, value in signature.parameters.items():
            if key not in ['self']:
                clean_parameters[key] = value
        signature._parameters = MappingProxyType(clean_parameters)

        # replace lazy annotations (str) with resolved ones
        for parameter_name, parameter in signature.parameters.items():
            if not isinstance(parameter.annotation, str):
                continue

            if parameter_name in type_hints:
                parameter._annotation = type_hints[parameter_name]

        # replace lazy return annotation (str) with resolved one
        if isinstance(signature.return_annotation, str) and 'return' in type_hints:
            signature._return_annotation = type_hints['return']

        # nice output
        return f'{definition} {name}{signature}'
```

**Comment by NiklasRosenstein** [comment]
Hey @vemel,

In the current `develop` version (going to be v3.x) the code is parsed with `lib2to3` and thus annotations will be rendered in the docs just like they are in the code. I do not plan to improve the situation in v2, but feel free to open a PR against the master branch if you want this in v2.

**Comment by vemel** [comment]
Hi @NiklasRosenstein . Thank you a lot, this works. BTW< take a look at https://pypi.org/project/pytypes/ . These guys made `get_type_hints` function usable, so probably it could help youa s well.

**Comment by leonoverweel** [comment]
Hey @NiklasRosenstein, great to hear there's support for this in v3! Do you have any idea of your timeline for when you're planning to release v3?

**Comment by NiklasRosenstein** [comment]
Hey @leonoverweel ,

It's already in a pretty good state, so I am thinking of cutting a release soon. However the two key main features that are missing now compared to the current 2.x version is the Mkdocs integration and the "simple" command-line interface.

You could give it a spin from the `develop` branch and share feedback if you like 🙂

**Comment by NiklasRosenstein** [comment]
In the meantime, I am going to close this issue as this is already working in the `develop` branch (see below for an example).

https://github.com/NiklasRosenstein/pydoc-markdown/blob/0e126a8f4c28fb5d7436ea4388b87d1087f2dc5a/src/tests/pydoc_markdown/test_e2e_markdown.py#L19-L36
