### ISSUE TITLE
Explicitly Specify PyYAML loader to silence warning

### ISSUE THREAD

**Issue by ian-bunner** [NiklasRosenstein/pydoc-markdown#87]
Details here: https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation

to fix change line 47 in pydocmd/__main.py__ to read:
    config = yaml.load(fp, Loader=yaml.FullLoader)

**Comment by NiklasRosenstein** [comment]
This was added to pydoc-markdown 2.x in 4c845e06919417a1cd1fa8cc6c2a7819451940e0. Going to release v2.1.0 with this change today.
