### ISSUE TITLE
[develop] Broken links in table of contents

### ISSUE THREAD

**Issue by grwlf** [NiklasRosenstein/pydoc-markdown#97]
Hi. I'm using current develop's branch HEAD (2db7223).

The development version of the tool generates table of contents, but unfortunately references in it don't work. [Example](https://github.com/stagedml/pylightnix/blob/47010ee2a8629f6520d1d4e69936b598bf852fc1/docs/Reference.md):

```
# Table of Contents

  * [pylightnix.types](#pylightnix.types)
    * [Path](#pylightnix.types.Path)
    * [Hash](#pylightnix.types.Hash)
    * [HashPart](#pylightnix.types.HashPart)

....

# `pylightnix.types`
## `Path` Objects
## `Hash` Objects
## `HashPart` Objects

...

```

**Comment by grwlf** [comment]
Meanwhile I implemented a workaround which adds '<a name={correct_object_id}></a>' anchor before every header. I don't like adding HTML to markdown, but I couldn't find a better solution quickly.

**Comment by NiklasRosenstein** [comment]
Hey @grwlf,

Unfortunately I don't think there is a better solution to this. As far as I know, there is nothing in the Markdown spec to override the anchor name of a header. There is an `html_headings` option already. I like your solution as well and I think people should have the choice, so I'm going add it as a `insert_heading_anchors` option.

**Comment by NiklasRosenstein** [comment]
Going to change the label to "enhancement" as this is a Markdown limitation that we can only work around.
